--- 
framework: jest
parallelism: 1
postMerge:
  pattern: 
    - ./test/algorithms/geometric-test.js
postRun: 
  command:
    - "node --version"
preMerge: 
  pattern: 
    - ./test/algorithms/geometric-test.js
preRun: 
  command:
    - npm i
    - npm run react
stability:  
  consecutive_runs: 5
version: 1.7
