--- 
framework: jest
modifiers: 
  - 
    cli: "--forbid-pending --no-bail"
    type: jest
postMerge: 
  env:
  envname1: postmerge1
  envname2: postmerge2
  pattern: 
    - ./test/algorithms/geometric-test.js
  strategy: 
    threshold: <5|100s|30m|6h>
    type: <commit|time>
postRun: 
  - "node --version"
preMerge: 
  env: 
    envname3: premerge3
    envname4: premerge4
  pattern: 
    - ./test/algorithms/geometric-test.js
preRun: 
  commands: 
    - "npm i"
    - "npm run react"
  env: 
    envname5: prerun5
stability: 
  consecutive_runs: 
