
--- 
framework: jasmine
licenseTier: xsmall
postMerge: 
  pattern: 
    - ./test/algorithms/geometric-test.js
  strategy: 
    threshold: 2
    type: AfterNthCommitStrategy
postRun: 
  command:
    - "node --version"
preMerge: 
  pattern: 
    - ./test/algorithms/geometric-test.js
preRun: 
  command:
    - "npm i"
stability:  
  consecutive_runs: 5
version: 2.0
