
--- 
framework: jest
tier: large
postMerge: 
  pattern: 
    - ./test/algorithms/geometric-test.js
  strategy: 
    threshold: 2
    name: AfterNthCommitStrategy
postRun: 
  command:
    - "node --version"
preMerge: 
  pattern: 
    - ./test/algorithms/geometric-test.js
preRun: 
  command:
    - npm i
    - npm run react
stability:  
  consecutive_runs: 5
version: 2.0
