
--- 
framework: jest
modifiers: 
  - type: jest
    cli: "--forbid-pending --no-bail"
postMerge: 
  pattern: 
    - ./test/algorithms/geometric-test.js
  strategy: 
    threshold: <5|100s|30m|6h>
    type: <commit|time>
postRun: 
    - "node --version"
preMerge: 
  pattern: 
    - ./test/algorithms/geometric-test.js
preRun: 
    - "npm i"
    - "npm run react"
stability:  
  consecutive_runs: 5
version: 2.0
