
--- 
framework: jest
blocklist: 
 - "test/algorithms/geometric-test.js##geometric algorithm##should have inverse functions for getPosition and getValue##"
postMerge:
  pattern: 
    - ./test/algorithms/geometric-test.js
postRun: 
  command:
    - "node --version"
preMerge: 
  pattern: 
    - ./test/algorithms/geometric-test.js
preRun: 
  command:
    - npm i
    - npm run react
stability:  
  consecutive_runs: 5
version: 1.3
